name: NetworkLevelling
version: '${project.version}'
main: rankednetwork.Main
api-version: 1.19
commands:
  booster:
    description: Commands to manage boosters
    usage:  /booster <create,remove,give,activate,stats>
