name: NetworkLevelling
version: '${project.version}'
main: rankednetwork.Main
api-version: 1.19
commands:
  bos:
    description: Commands to manage boosters
    usage: /booster help
    aliases:
      - booster
